const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnHoldGesture,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Button.Acts.SetCSSStyle
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Platform: 0},
	{DragDrop: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{Sprite2: 0},
	{Text: 0},
	{Button: 0},
	{Sprite4: 0},
	{Sprite3: 0},
	{Text2: 0},
	{Button2: 0},
	{רכבתהחגים: 0},
	{Button3: 0},
	{איךמשחקים: 0},
	{Button4: 0},
	{כלהכבוד: 0},
	{שוב: 0},
	{Button5: 0},
	{Touch: 0},
	{Lives: 0},
	{נקודות: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	רכבתהחגים: class extends self.ISpriteInstance {},
	Button3: class extends self.IButtonInstance {},
	איךמשחקים: class extends self.ISpriteInstance {},
	Button4: class extends self.IButtonInstance {},
	כלהכבוד: class extends self.ISpriteInstance {},
	שוב: class extends self.IButtonInstance {},
	Button5: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {}
}